# 이렇게 하면 어떨까, 아이디어 스케치
# 변수 정의
BINARY_DIR := bin
PROJECT_PREFIX := wb

# 빌드 타겟
.PHONY: all collector analyzer server clean

all: collector analyzer server

collector:
	go build -o $(BINARY_DIR)/$(PROJECT_PREFIX)Collector ./cmd/collector

analyzer:
	go build -o $(BINARY_DIR)/$(PROJECT_PREFIX)Analyzer ./cmd/analyzer

server:
	go build -o $(BINARY_DIR)/$(PROJECT_PREFIX)Server ./cmd/server

# 프론트엔드 빌드
frontend:
	cd frontend && npm install && npm run build

# 전체 프로젝트 빌드
build-all: all frontend

# 클린 타겟
clean:
	rm -rf $(BINARY_DIR)/*

# 실행 타겟
run-collector:
	./$(BINARY_DIR)/$(PROJECT_PREFIX)Collector

run-analyzer:
	./$(BINARY_DIR)/$(PROJECT_PREFIX)Analyzer

run-server:
	./$(BINARY_DIR)/$(PROJECT_PREFIX)Server

# 테스트 타겟
test:
	go test ./...

# 도커 빌드 (옵션)
docker-build:
	docker build -t wasabibucket .

# 도커 실행 (옵션)
docker-run:
	docker run wasabibucket
